services:
  dns-api-mock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dns-api-mock
    ports:
      - "8443:8443"
    environment:
      REMOTE_DNS: ${REMOTE_DNS:-8.8.8.8}
      REMOTE_DNS_PORT: ${REMOTE_DNS_PORT:-53}
    volumes:
      - .:/app
    restart: unless-stopped
